# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.api.bitcoin_transactions_api import BitcoinTransactionsApi  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestBitcoinTransactionsApi(unittest.TestCase):
    """BitcoinTransactionsApi unit test stubs"""

    def setUp(self):
        self.api = blocwatch_v1.api.bitcoin_transactions_api.BitcoinTransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        getTransaction  # noqa: E501
        """
        pass

    def test_get_transaction_input(self):
        """Test case for get_transaction_input

        getTransactionInput  # noqa: E501
        """
        pass

    def test_get_transaction_output(self):
        """Test case for get_transaction_output

        getTransactionOutput  # noqa: E501
        """
        pass

    def test_list_transactions(self):
        """Test case for list_transactions

        listTransactions  # noqa: E501
        """
        pass

    def test_list_transactions_inputs(self):
        """Test case for list_transactions_inputs

        listTransactionsInputs  # noqa: E501
        """
        pass

    def test_list_transactions_outputs(self):
        """Test case for list_transactions_outputs

        listTransactionsOutputs  # noqa: E501
        """
        pass

    def test_search_transactions(self):
        """Test case for search_transactions

        searchTransactions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
