# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.api.bitcoin_addresses_api import BitcoinAddressesApi  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestBitcoinAddressesApi(unittest.TestCase):
    """BitcoinAddressesApi unit test stubs"""

    def setUp(self):
        self.api = blocwatch_v1.api.bitcoin_addresses_api.BitcoinAddressesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_address(self):
        """Test case for get_address

        getAddress  # noqa: E501
        """
        pass

    def test_list_address_usages(self):
        """Test case for list_address_usages

        listAddressUsages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
