# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.models.usage_in import UsageIn  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestUsageIn(unittest.TestCase):
    """UsageIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsageIn(self):
        """Test UsageIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blocwatch_v1.models.usage_in.UsageIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
