# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.models.bitcoin_input import BitcoinInput  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestBitcoinInput(unittest.TestCase):
    """BitcoinInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBitcoinInput(self):
        """Test BitcoinInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blocwatch_v1.models.bitcoin_input.BitcoinInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
