# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.models.list_transaction_outputs_response import ListTransactionOutputsResponse  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestListTransactionOutputsResponse(unittest.TestCase):
    """ListTransactionOutputsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListTransactionOutputsResponse(self):
        """Test ListTransactionOutputsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blocwatch_v1.models.list_transaction_outputs_response.ListTransactionOutputsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
