# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.api.bitcoin_blocks_api import BitcoinBlocksApi  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestBitcoinBlocksApi(unittest.TestCase):
    """BitcoinBlocksApi unit test stubs"""

    def setUp(self):
        self.api = blocwatch_v1.api.bitcoin_blocks_api.BitcoinBlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_block(self):
        """Test case for get_block

        getBlock  # noqa: E501
        """
        pass

    def test_get_top_block(self):
        """Test case for get_top_block

        getTopBlock  # noqa: E501
        """
        pass

    def test_list_block_transactions(self):
        """Test case for list_block_transactions

        listBlockTransactions  # noqa: E501
        """
        pass

    def test_list_blocks(self):
        """Test case for list_blocks

        listBlocks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
