# coding: utf-8

"""
    Blocwatch REST API

    The premier crypto API for blockchain analysis  # noqa: E501

    OpenAPI spec version: Alpha v.0.0.1
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import blocwatch_v1
from blocwatch_v1.models.bitcoin_search_request import BitcoinSearchRequest  # noqa: E501
from blocwatch_v1.rest import ApiException


class TestBitcoinSearchRequest(unittest.TestCase):
    """BitcoinSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBitcoinSearchRequest(self):
        """Test BitcoinSearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blocwatch_v1.models.bitcoin_search_request.BitcoinSearchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
