# coding: utf-8

"""
    Blocwatch REST API

    The premier API for blockchain analysis  # noqa: E501

    OpenAPI spec version: v1.0.0
    Contact: support@blocwatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

import blocwatch_v1.bitcoin.grouped_summary  # noqa: F401,E501


class SummarizeTransactionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'summaries': 'list[GroupedSummary]'
    }

    attribute_map = {
        'summaries': 'summaries'
    }

    def __init__(self, summaries=None):  # noqa: E501
        """SummarizeTransactionsResponse - a model defined in Swagger"""  # noqa: E501

        self._summaries = None
        self.discriminator = None

        if summaries is not None:
            self.summaries = summaries

    @property
    def summaries(self):
        """Gets the summaries of this SummarizeTransactionsResponse.  # noqa: E501

        The requested summaries.  # noqa: E501

        :return: The summaries of this SummarizeTransactionsResponse.  # noqa: E501
        :rtype: list[GroupedSummary]
        """
        return self._summaries

    @summaries.setter
    def summaries(self, summaries):
        """Sets the summaries of this SummarizeTransactionsResponse.

        The requested summaries.  # noqa: E501

        :param summaries: The summaries of this SummarizeTransactionsResponse.  # noqa: E501
        :type: list[GroupedSummary]
        """

        self._summaries = summaries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SummarizeTransactionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SummarizeTransactionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
